// SPDX-License-Identifier: Apache-2.0
// tb_trinity_merkle_agg.v — Testbench for L-S45 Trinity Merkle Aggregator (Wave-12b)
//
// 88 test patterns:
//   [00..07] — 8 deterministic 4-leaf patterns (all-zero, all-ones, single-bit,
//               ascending, descending, mixed, alternating)
//   [08..87] — 80 LFSR-seeded random 4-leaf streams
//
// Golden reference: Python gen_merkle_golden.py (same 3-round XOR+rotate combiner)
//   hash_combine(a,b):
//     s0  = a ^ b
//     s1  = rotl64(s0, 5)  ^ a
//     s2  = rotl64(s1, 11) ^ b
//     out = rotl64(s2, 22) ^ a ^ b
//
// Token: TRINITY_MERKLE_AGG_GREEN
//
// DUT latency: 2 cycles (1 pipeline reg for nodes, 1 for root)
//
`default_nettype none
`timescale 1ns/1ps

module tb_trinity_merkle_agg;

    // ----------------------------------------------------------------
    // DUT signals
    // ----------------------------------------------------------------
    reg         clk;
    reg         rst_n;
    reg  [63:0] leaf0, leaf1, leaf2, leaf3;
    reg         leaves_valid;
    wire [63:0] root;
    wire        root_valid;

    // ----------------------------------------------------------------
    // DUT instantiation
    // ----------------------------------------------------------------
    trinity_merkle_agg dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .leaf0        (leaf0),
        .leaf1        (leaf1),
        .leaf2        (leaf2),
        .leaf3        (leaf3),
        .leaves_valid (leaves_valid),
        .root         (root),
        .root_valid   (root_valid)
    );

    // ----------------------------------------------------------------
    // Clock: 10 ns period
    // ----------------------------------------------------------------
    initial clk = 0;
    always #5 clk = ~clk;

    // ----------------------------------------------------------------
    // Test vectors — stim[i] = {leaf3, leaf2, leaf1, leaf0}
    // ----------------------------------------------------------------
    reg [255:0] stim [0:87];
    reg [63:0]  gold [0:87];

    // Expected root queue (FIFO depth = 2 for pipeline latency)
    reg [63:0]  exp_fifo [0:1];
    integer     exp_wp, exp_rp;

    integer i;
    integer pass_cnt, fail_cnt;

    // ----------------------------------------------------------------
    // Golden vector initialisation (generated by gen_merkle_golden.py)
    // ----------------------------------------------------------------
    initial begin
        // [00] all_zero
        stim[0] = 256'h0000000000000000_0000000000000000_0000000000000000_0000000000000000;
        gold[0] = 64'h0000000000000000;
        // [01] all_ones
        stim[1] = 256'hFFFFFFFFFFFFFFFF_FFFFFFFFFFFFFFFF_FFFFFFFFFFFFFFFF_FFFFFFFFFFFFFFFF;
        gold[1] = 64'h0000000000000000;
        // [02] single_bit_L0
        stim[2] = 256'h0000000000000000_0000000000000000_0000000000000000_0000000000000001;
        gold[2] = 64'h0000000000001005;
        // [03] single_bit_L1
        stim[3] = 256'h0000000000000000_0000000000000000_8000000000000000_0000000000000000;
        gold[3] = 64'h8840000100200840;
        // [04] ascending
        stim[4] = 256'h18191A1B1C1D1E1F_1011121314151617_08090A0B0C0D0E0F_0001020304050607;
        gold[4] = 64'h66524E3A36021E6A;
        // [05] descending
        stim[5] = 256'hE0E1E2E3E4E5E6E7_E8E9EAEBECEDEEEF_F0F1F2F3F4F5F6F7_F8F9FAFBFCFDFEFF;
        gold[5] = 64'h0A3E22565A6E7206;
        // [06] mixed
        stim[6] = 256'hA5A5A5A5A5A5A5A5_FEDCBA9876543210_0123456789ABCDEF_DEADBEEFCAFEBABE;
        gold[6] = 64'h25AFE3A550F5E7F5;
        // [07] alternating
        stim[7] = 256'hCCCCCCCCCCCCCCCC_3333333333333333_AAAAAAAAAAAAAAAA_5555555555555555;
        gold[7] = 64'h5555555555555555;
        // [08] lfsr_00
        stim[8] = 256'h2B16158BBEC5EB62_616230B1AC58562C_0E27B313ED89C2C4_E2707138389C1C4E;
        gold[8] = 64'h74146B563BFBB0E6;
        // [09] lfsr_01
        stim[9] = 256'hF069CC34661A330D_8E9DF34E79A788D3_11DBBCEDEA76753B_75B18ED8476C23B6;
        gold[9] = 64'h9E670BB809A059F9;
        // [10] lfsr_02
        stim[10] = 256'hF3BDCDDE66EF8777_B3DDEDEE76F78F7B_7DD83EEC1F760FBB_AD8656C39F61FBB0;
        gold[10] = 64'h47262A2605C11273;
        // [11] lfsr_03
        stim[11] = 256'hDDF86EFC377E1BBF_878FF7C7CFE3D3F1_80FBF47DCE3E671F_F7BBCFDDD3EE69F7;
        gold[11] = 64'hA804E7EC56DF583E;
        // [12] lfsr_04
        stim[12] = 256'h19D60CEBB275ED3A_F561CEB0675833AC_DE1DDB0E6D8782C3_B9DFE8EFC077D43B;
        gold[12] = 64'hECD721739C085C32;
        // [13] lfsr_05
        stim[13] = 256'hC9D7D0EBDC75DA3A_AD7E56BF9F5FFBAF_FFE9CBF465FA32FD_769D8F4E47A797D3;
        gold[13] = 64'hD65D196CC3A4E0C4;
        // [14] lfsr_06
        stim[14] = 256'h4D16268BA745E7A2_1965B8B25C599A2C_FE51CB28659432CA_6D1D828E414794A3;
        gold[14] = 64'hC26636303A822A6C;
        // [15] lfsr_07
        stim[15] = 256'h8019F40C7A063D03_F99BC8CDD0666833_11BDBCDE5E6F9B37_73D18DE846F4237A;
        gold[15] = 64'h909B60B1AC148E8D;
        // [16] lfsr_08
        stim[16] = 256'h265C132E0997B0CB_B5C25AE199704CB8_1C280E14070A0385_AA81E14070A03850;
        gold[16] = 64'h3EA605C9BA347050;
        // [17] lfsr_09
        stim[17] = 256'h5D322E99A34C51A6_732439921CC9BA64_42462123A491E648_EC65C2326119848C;
        gold[17] = 64'h932558B402ADBF13;
        // [18] lfsr_10
        stim[18] = 256'h0FB1B3D859EC2CF6_FB107D883EC41F62_390DA88654439E21_28D3A069E434721A;
        gold[18] = 64'h7D2A2D7E57DFDB52;
        // [19] lfsr_11
        stim[19] = 256'hC59662CB8565F6B2_696E34B7AE5BE32D_8EE7F373CDB9D2DC_167BBF3DEB9E75CF;
        gold[19] = 64'h67F6CB8CB81959AD;
        // [20] lfsr_12
        stim[20] = 256'h3FEDABF655FB9EFD_46D39769FFB47FDA_A535E69A734D8DA6_7B5989AC44D6226B;
        gold[20] = 64'hB086885FF5D9CFB9;
        // [21] lfsr_13
        stim[21] = 256'h895444AA2255A52A_6D4B82A5F5527AA9_CCB7D25BDD2DDA96_FB7E7DBF8ADFF16F;
        gold[21] = 64'h7671942B5ED43A36;
        // [22] lfsr_14
        stim[22] = 256'h9361FDB07ED83F6C_A61A530D9D864EC3_49A990D4486A2435_52959D4A4EA59352;
        gold[22] = 64'h0C1586A439ED2E26;
        // [23] lfsr_15
        stim[23] = 256'hDD0E6E878343F5A1_88EFF077CC3BD21D_76FB8F7DF3BE79DF_1FB60FDBB3EDEDF6;
        gold[23] = 64'hC5EE222575E82DAE;
        // [24] lfsr_16
        stim[24] = 256'hCC8466423321AD90_F84E7C278A13F109_0CEDB276593B989D_CED0676833B419DA;
        gold[24] = 64'h4D6BBFF0AB411A6F;
        // [25] lfsr_17
        stim[25] = 256'h795188A84454222A_E516728B8D45F2A2_B16C58B62C5BA22D_56C82B6415B20AD9;
        gold[25] = 64'h18D2FB17F9F57799;
        // [26] lfsr_18
        stim[26] = 256'hA3A5E5D272E98D74_1259BD2C5E962F4B_4D9192C8496424B2_1115BC8A5E459B22;
        gold[26] = 64'hED377288F6792008;
        // [27] lfsr_19
        stim[27] = 256'h7F658BB245D996EC_8656432B9595FECA_9D6BFAB5C95A64AD_46BA235DA5AE52D7;
        gold[27] = 64'h8299CD7915CDE2C6;
        // [28] lfsr_20
        stim[28] = 256'h89EBF0F5CC7A663D_66BB875DF7AE7BD7_73B78DDBF2EDCD76_4B7625BBA6DDE76E;
        gold[28] = 64'h2D0F2F46083347C0;
        // [29] lfsr_21
        stim[29] = 256'h60238411F6087B04_1A37B91BE88DC046_CB71D1B868DC346E_871E438F95C7FEE3;
        gold[29] = 64'h054A516A825BC54B;
        // [30] lfsr_22
        stim[30] = 256'hF3EE79F788FBF07D_B6EDEF7677BB8FDD_2ED8176C0BB605DB_3D821EC1BB605DB0;
        gold[30] = 64'h0813A0C13A02BC82;
        // [31] lfsr_23
        stim[31] = 256'hED77C2BBD55DDEAE_377C1BBE0DDFB2EF_CFC3D3E1DDF06EF8_CC3E661F870FF787;
        gold[31] = 64'hCE129D240CBF2575;
        // [32] lfsr_24
        stim[32] = 256'h652F8697F74BCFA5_4AF7917BFCBDCA5E_677587BA43DD95EE_6F5783ABF5D5CEEA;
        gold[32] = 64'h520B77100B26C899;
        // [33] lfsr_25
        stim[33] = 256'h34281A140D0A0685_FA83C941D0A06850_203DA41E520F9D07_D3D269E980F4407A;
        gold[33] = 64'h48409DC376800721;
        // [34] lfsr_26
        stim[34] = 256'h64063203AD01E280_58679833F819C80C_2674133A099DB0CE_B7425BA199D04CE8;
        gold[34] = 64'h7E33132F893A0373;
        // [35] lfsr_27
        stim[35] = 256'h1327BD93EAC9C164_5A7199384C9C264E_0714038A01C5B4E2_714038A01C500E28;
        gold[35] = 64'h50F966F3746157D2;
        // [36] lfsr_28
        stim[36] = 256'h08D3B069EC34761A_8D304698234C11A6_2B0BA185E4C27261_60B23059AC2C5616;
        gold[36] = 64'h61AFD7C94029BBA8;
        // [37] lfsr_29
        stim[37] = 256'h3B7BA9BDE0DE706F_0FB3B3D9EDEC76F6_FB307D983ECC1F66_3B0DA98654C39E61;
        gold[37] = 64'h13C37B7676042DFF;
        // [38] lfsr_30
        stim[38] = 256'h59D198E84C74263A_3D141E8A0F45B3A2_694380A1F4507A28_8C37F21BCD0DD286;
        gold[38] = 64'hDB350F3A7E94A116;
        // [39] lfsr_31
        stim[39] = 256'h8E11F30879843CC2_191BB88DE8467423_F9B1C8D8646C3236_131DBD8E5EC79B63;
        gold[39] = 64'h1D0484FC72573DFF;
        // [40] lfsr_32
        stim[40] = 256'h70678C33F219CD0C_76763B3BA99DE0CE_17660BB3B1D9ECEC_1E61BB305D982ECC;
        gold[40] = 64'h278F516BCAAE1DEA;
        // [41] lfsr_33
        stim[41] = 256'h7C318A18450C2286_B316598B98C5F862_716838B41C5A0E2D_66863343ADA1E2D0;
        gold[41] = 64'hBF57B9E9DE096E1D;
        // [42] lfsr_34
        stim[42] = 256'hA71A538D9DC64EE3_59A998D44C6A2635_3A941D4A0EA5B352_1143BCA1EA507528;
        gold[42] = 64'h0B60918070AE87F6;
        // [43] lfsr_35
        stim[43] = 256'h8987F0C3CC61D230_607B843DF61E7B0F_1FB7BBDBE9EDC0F6_9371FDB87EDC3F6E;
        gold[43] = 64'hDDCB4BC2A6B25396;
        // [44] lfsr_36
        stim[44] = 256'hA35A51AD9CD64E6B_1DA9BAD45D6A2EB5_B291ED4876A43B52_6918348C1A460D23;
        gold[44] = 64'hA34E8F60480ED916;
        // [45] lfsr_37
        stim[45] = 256'h8C7DF23E791F888F_3FDBABEDE1F670FB_45B396D9FF6C7FB6_9335FD9A7ECD8B66;
        gold[45] = 64'hE760A8710CF82BD4;
        // [46] lfsr_38
        stim[46] = 256'hB1CE58E79873F839_5CE82E74173A0B9D_6E8437421BA1B9D0_F047CC23D211DD08;
        gold[46] = 64'h42A12CE133C524E8;
        // [47] lfsr_39
        stim[47] = 256'hB58A5AC599624CB1_18A80C54062A0315_E281C54062A03150_C81C640E3207AD03;
        gold[47] = 64'h99CEC401B32C9A8F;
        // [48] lfsr_40
        stim[48] = 256'h2975A0BA505D9C2E_475223A9A5D452EA_BD25EA9275498EA4_9258492C2496124B;
        gold[48] = 64'h6F0279BA8079B1C7;
        // [49] lfsr_41
        stim[49] = 256'h760D8F06478397C1_10D6086BB035EC1A_656186B0435821AC_4E17930BFD85CAC2;
        gold[49] = 64'hA22323C33C5C4A4D;
        // [50] lfsr_42
        stim[50] = 256'hD9BFD8DFD86FD837_C3FFD5FFDEFFDB7F_0FFE07FFB7FFEFFF_FFE07FF03FF81FFC;
        gold[50] = 64'h115B3B6CCD40A8DB;
        // [51] lfsr_43
        stim[51] = 256'h01EA00F5B47A5A3D_1EA00F5007A803D4_8201F5007A803D40_D81BD80DD8066C03;
        gold[51] = 64'hBF8043D4B65FC6D1;
        // [52] lfsr_44
        stim[52] = 256'hA32251919CC84E64_1A29B9145C8A2E45_CA91D14868A43452_991E4C8F9247FD23;
        gold[52] = 64'h18C9E5E692E3495C;
        // [53] lfsr_45
        stim[53] = 256'h6217850BF685CF42_3977A8BBE05DC42E_2F73A3B9E5DC72EE_27321399BDCC5EE6;
        gold[53] = 64'h22283F61BE538A1C;
        // [54] lfsr_46
        stim[54] = 256'hDC006E0037001B80_980FF807C803D001_10FA087DB03E581F_67A187D043E821F4;
        gold[54] = 64'h9E26AC7ACC818177;
        // [55] lfsr_47
        stim[55] = 256'hF6607B303D981ECC_EE0DC306618384C1_00DC006E0037B41B_0DC006E0037001B8;
        gold[55] = 64'h0A7D23F594FE0D02;
        // [56] lfsr_48
        stim[56] = 256'hD287DD43DAA1D950_707F8C3FF21FCD0F_77F63BFBA9FDE0FE_0F6607B3B7D9EFEC;
        gold[56] = 64'h16442358104AE25E;
        // [57] lfsr_49
        stim[57] = 256'hE72273918DC846E4_922C4916248BA645_B2CA596598B24C59_6CA836541B2A0D95;
        gold[57] = 64'h837351AA0370C075;
        // [58] lfsr_50
        stim[58] = 256'h3DB7AADBE16DC4B6_637385B9F6DC7B6E_2F37A39BE5CDC6E6_237211B9BCDC5E6E;
        gold[58] = 64'hD68072908774EFBB;
        // [59] lfsr_51
        stim[59] = 256'h9D41FAA07D503EA8_441A220DA5065283_89A5F0D278698834_625B852DF6967B4B;
        gold[59] = 64'h1708B6E819F6ED6D;
        // [60] lfsr_52
        stim[60] = 256'hD113DC89DA446D22_493F909FFC4FCA27_5BF599FA4CFD927E_1F540FAA07D5B7EA;
        gold[60] = 64'hDA024443F4BB2D3C;
        // [61] lfsr_53
        stim[61] = 256'hC93DD09E684F8027_A3DE51EF9CF7FA7B_15E9BEF45F7A2FBD_3691AF4857A42BD2;
        gold[61] = 64'h00F72EA6F2EDA847;
        // [62] lfsr_54
        stim[62] = 256'hEF5C77AE3BD7A9EB_15CC0AE60573B6B9_34C1AE6057302B98_F413CE09D3046982;
        gold[62] = 64'h3000354C39BF19B3;
        // [63] lfsr_55
        stim[63] = 256'hB91A5C8D9A464D23_D1A868D4346A1A35_428F9547FEA3CB51_E0F5C47A623D851E;
        gold[63] = 64'h327F3948D0D33145;
        // [64] lfsr_56
        stim[64] = 256'h9337FD9BCACDD166_A37A51BD9CDE4E6F_1FA9BBD45DEA2EF5_9291FD487EA43F52;
        gold[64] = 64'hE3F13E63453555D1;
        // [65] lfsr_57
        stim[65] = 256'h08C5B06258319818_8C5046282314118A_3D0BAA85E14270A1_68B38059F42C7A16;
        gold[65] = 64'h9B4C298BD46144B7;
        // [66] lfsr_58
        stim[66] = 256'hEEEA77758FBA47DD_0EAC075603ABB5D5_EAC075603AB01D58_4C0C26061303BD81;
        gold[66] = 64'h21C7C21E750E6699;
        // [67] lfsr_59
        stim[67] = 256'h6D7A36BDAF5E57AF_CFA7D3D3DDE9DAF4_CA7E653F869FF74F_97EE4BF791FBFCFD;
        gold[67] = 64'h15CAF397D4C72FE4;
        // [68] lfsr_60
        stim[68] = 256'h6E6037301B980DCC_FE07CB03D181DCC0_687D803E401F940F_9FD7FBEBC9F5D0FA;
        gold[68] = 64'h0FE13BC3C9EC055C;
        // [69] lfsr_61
        stim[69] = 256'h7B4789A3F0D1CC68_C476623B851DF68E_776E3BB7A9DBE0ED_06E60373B5B9EEDC;
        gold[69] = 64'hE8914D5CBD938AFB;
        // [70] lfsr_62
        stim[70] = 256'h74E43A721D39BA9C_3E461F23BB91E9C8_5C639A31F9187C8C_6634331A198DB8C6;
        gold[70] = 64'h1C196860C64D4E31;
        // [71] lfsr_63
        stim[71] = 256'hFDE67EF38B79F1BC_566D9F364F9B93CD_C6D4636A31B5ACDA_5D4E2EA7A353E5A9;
        gold[71] = 64'h858C448CE4410FF0;
        // [72] lfsr_64
        stim[72] = 256'hBB4C5DA62ED3A369_F4C87A643D321E99_C48DD6466B238191_78DE3C6FAA37E11B;
        gold[72] = 64'hD73BC9867C2548CF;
        // [73] lfsr_65
        stim[73] = 256'h442C2216110BBC85_8AC5F16278B18858_545B9E2DFB167D8B_E5B472DA396DA8B6;
        gold[73] = 64'h7E79964DD7821997;
        // [74] lfsr_66
        stim[74] = 256'h9C83FA41C9206490_583A2C1DA20E5107_23A411D208E9B074_EA4275218E904748;
        gold[74] = 64'h3E0A213D51F15B85;
        // [75] lfsr_67
        stim[75] = 256'h2817A00BE405C602_517228B9A05C502E_B7245B922DC9A2E4_324819240C920649;
        gold[75] = 64'hC40E936197910948;
        // [76] lfsr_68
        stim[76] = 256'h8F9047C823E411F2_010BB485EE427721_10B00858042C0216_6301858042C02160;
        gold[76] = 64'h433161CCC9B6417D;
        // [77] lfsr_69
        stim[77] = 256'h0DFA06FDB77E5BBF_DFA06FD037E81BF4_A20FE507C683D741_08F9B07C583E2C1F;
        gold[77] = 64'hF0BEEB931205AA4A;
        // [78] lfsr_70
        stim[78] = 256'h19D40CEA0675B73A_F541CEA0675033A8_DC1DDA0E6D078283_99DFF8EFC877D03B;
        gold[78] = 64'h5D77D1337C2C2731;
        // [79] lfsr_71
        stim[79] = 256'h3155ACAA56559F2A_AD53E2A9C55462AA_FD39CA9C654E32A7_5B9D99CE4CE79273;
        gold[79] = 64'h8715E91EB8501637;
        // [80] lfsr_72
        stim[80] = 256'h6BE035F01AF80D7C_A607E703C781D7C0_4879903C481E240F_4F9593CA49E590F2;
        gold[80] = 64'h3F6D42B6596F9657;
        // [81] lfsr_73
        stim[81] = 256'h7F3B8B9DF1CE78E7_83B641DB94EDFE76_C36BD5B5DEDA6F6D_06BE035FB5AFEED7;
        gold[81] = 64'h9D7E89BF0F07203E;
        // [82] lfsr_74
        stim[82] = 256'h062BB715EF8A77C5_62B0315818AC0C56_3307AD83E2C1C560_8873F039CC1C660E;
        gold[82] = 64'h433BF00DE530E6CE;
        // [83] lfsr_75
        stim[83] = 256'hD995D8CA6C658232_C15FD4AFDE57DB2B_25FE12FFBD7FEABF_8FE247F197F84BFC;
        gold[83] = 64'h36791F2DD33CA3E1;
        // [84] lfsr_76
        stim[84] = 256'hA34E51A79CD3FA69_1CE9BA745D3A2E9D_A691E74873A439D2_4119948C4A462523;
        gold[84] = 64'hE80D81623C625D0A;
        // [85] lfsr_77
        stim[85] = 256'hA16E50B79C5BFA2D_3EE9AB7455BA2ADD_56939F49FBA47DD2_C934649A324DAD26;
        gold[85] = 64'h842CE16B74069641;
        // [86] lfsr_78
        stim[86] = 256'hA393E5C9C6E46372_1139BC9C5E4E2F27_7B9189C844E42272_C916648B8645F722;
        gold[86] = 64'h7155A4CAFA7B1621;
        // [87] lfsr_79
        stim[87] = 256'hAAD9E16C70B6385B_8599F6CC7B663DB3_A19BE4CDC6666333_31B9ACDC566E2B37;
        gold[87] = 64'h86CE9230AB840C9F;
    end

    // ----------------------------------------------------------------
    // Main stimulus + checker
    // ----------------------------------------------------------------
    initial begin
        // Reset
        rst_n        = 0;
        leaf0        = 0;
        leaf1        = 0;
        leaf2        = 0;
        leaf3        = 0;
        leaves_valid = 0;
        pass_cnt     = 0;
        fail_cnt     = 0;
        exp_wp       = 0;
        exp_rp       = 0;

        @(posedge clk); #1;
        @(posedge clk); #1;
        rst_n = 1;
        @(posedge clk); #1;

        // ---- Drive all 88 test vectors, one per cycle ----
        for (i = 0; i < 88; i = i + 1) begin
            leaf0        = stim[i][63:0];
            leaf1        = stim[i][127:64];
            leaf2        = stim[i][191:128];
            leaf3        = stim[i][255:192];
            leaves_valid = 1;
            // Enqueue expected root into FIFO
            exp_fifo[exp_wp % 2] = gold[i];
            exp_wp = exp_wp + 1;
            @(posedge clk); #1;
        end

        // Drain pipeline: 2 extra cycles to flush (pipeline latency = 2)
        leaves_valid = 0;
        @(posedge clk); #1;
        @(posedge clk); #1;
        @(posedge clk); #1;  // extra safety margin

        // Report
        $display("");
        $display("=== trinity_merkle_agg sim results ===");
        $display("  Total tests : 88");
        $display("  PASS        : %0d", pass_cnt);
        $display("  FAIL        : %0d", fail_cnt);
        if (fail_cnt == 0 && pass_cnt == 88) begin
            $display("TRINITY_MERKLE_AGG_GREEN");
            $display("Hash combiner: 3-round XOR+rotate (R1=5, R2=11, R3=22)");
            $display("Byte-match: hardware root matches Python golden ref byte-for-byte.");
        end else begin
            $display("TRINITY_MERKLE_AGG_FAIL — %0d failures", fail_cnt);
        end
        $finish;
    end

    // ----------------------------------------------------------------
    // Output checker — fires on every root_valid assertion
    // ----------------------------------------------------------------
    reg [63:0] expected;
    integer    chk_idx;
    initial    chk_idx = 0;

    always @(posedge clk) begin
        if (root_valid && rst_n) begin
            expected = gold[chk_idx];
            if (root === expected) begin
                pass_cnt = pass_cnt + 1;
            end else begin
                $display("FAIL [%0d]: root=64'h%016h  expected=64'h%016h",
                         chk_idx, root, expected);
                fail_cnt = fail_cnt + 1;
            end
            chk_idx = chk_idx + 1;
        end
    end

    // ----------------------------------------------------------------
    // Timeout watchdog
    // ----------------------------------------------------------------
    initial begin
        #50000;
        $display("TIMEOUT — simulation did not finish");
        $finish;
    end

endmodule
`default_nettype wire
