#!/usr/bin/env bash
# =============================================================================
# scripts/eqy_check.sh — Yosys EQY formal equivalence checker
# =============================================================================
#
# Wave-24 · RVR-017 · Issue #4 Change N
# Anchor: phi^2 + phi^-2 = 3 · DOI 10.5281/zenodo.19227877
#
# PURPOSE
#   Wire Yosys EQY (open-source formal equivalence checking) between two
#   Verilog implementations of each target module:
#     GOLD  — build/t27c/<module>.v  (generated by `t27c gen-verilog`)
#     GATE  — src/<module>.v          (hand-written, TTSKY26c submission target)
#
#   This closes the "Coq→silicon gap": Coq theorems prove the t27 spec correct;
#   t27c emits Verilog from that spec; EQY proves the hand-written RTL is
#   bit-exactly equivalent to the generated RTL.
#
# MODULES UNDER AUDIT
#   gf16_mul         src/gf16_mul.v
#   gf16_add         src/gf16_add.v
#   gf16_dot4        src/gf16_dot4.v
#   trinity_gf16_tile  src/trinity_gf16_tile.v
#
# VERDICT STATES (R5-honest)
#   PASS    — EQY exited 0; formal equivalence confirmed this run
#   FAIL    — EQY exited non-zero; equivalence NOT confirmed
#   PENDING — t27c-generated reference file missing; check deferred
#             (see docs/EQY_CHECK.md "Current Status" for tracker)
#
# EVIDENCE SCHEMA (written to evidence/eqy_<GIT_SHA>_<module>.json)
#   {
#     "module":        string,
#     "src_sha":       string (SHA-256 of src file),
#     "t27c_sha":      string (SHA-256 of build/t27c file, or "MISSING"),
#     "eqy_version":   string (eqy --version output, or "NOT_INSTALLED"),
#     "yosys_version": string (yosys --version output, or "NOT_INSTALLED"),
#     "verdict":       "PASS" | "FAIL" | "PENDING",
#     "timestamp_utc": ISO-8601,
#     "evidence_path": string
#   }
#
# USAGE
#   bash scripts/eqy_check.sh
#   EQY_STRICT=1 bash scripts/eqy_check.sh   # exit 1 on PENDING (default: warn)
#
# TOOLCHAIN PINS (override via environment)
#   YOSYS_MIN_VERSION  default: "0.40"
#   EQY_MIN_VERSION    default: "0.1"  (eqy is part of yosys-eqy)
#   T27C_COMMIT        default: "9752bab4b81fe1a3abc66b13749c4ac412a74ee6" (HEAD at PR time)
#                      Set to the gHashTag/t27 commit that generated build/t27c/*.v
#
# REPRODUCTION RECIPE
#   1. pip install yosys-eqy  (or: nix-shell -p yosys-eqy)
#   2. T27C_COMMIT=9752bab4b81fe1a3abc66b13749c4ac412a74ee6 bash scripts/eqy_check.sh
#   3. cat evidence/eqy_*.json | python3 -m json.tool
#
# REFS
#   Issue #4 Change N: https://github.com/gHashTag/tt-trinity-gf16/issues/4
#   Issue #34 RVR-015: https://github.com/gHashTag/tt-trinity-gf16/issues/34
#   Yosys EQY docs:    https://github.com/YosysHQ/eqy
#   t27 upstream:      https://github.com/gHashTag/t27  commit T27C_COMMIT
#
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVIDENCE_DIR="${REPO_ROOT}/evidence"
BUILD_T27C_DIR="${REPO_ROOT}/build/t27c"
SRC_DIR="${REPO_ROOT}/src"

T27C_COMMIT="${T27C_COMMIT:-9752bab4b81fe1a3abc66b13749c4ac412a74ee6}"
YOSYS_MIN_VERSION="${YOSYS_MIN_VERSION:-0.40}"
EQY_MIN_VERSION="${EQY_MIN_VERSION:-0.1}"
EQY_STRICT="${EQY_STRICT:-0}"   # if 1, PENDING exits non-zero

# Modules under audit (Issue #4 Change N acceptance list)
MODULES=(
    "gf16_mul"
    "gf16_add"
    "gf16_dot4"
    "trinity_gf16_tile"
)

# Coq theorem citations per module (R14 — Coq citation map)
# Format: "MODULE:COQ_THEOREM_REF"
declare -A COQ_CITATIONS
COQ_CITATIONS["gf16_mul"]="t27/trios-coq/IGLA/gf16_precision.v::lucas_values_gf16_exact_n1"
COQ_CITATIONS["gf16_add"]="t27/trios-coq/IGLA/lucas_closure_gf16.v::lucas_closure_phi_sq"
COQ_CITATIONS["gf16_dot4"]="t27/trios-coq/IGLA/gf16_precision.v::lucas_4_eq_7"
COQ_CITATIONS["trinity_gf16_tile"]="t27/trios-coq/IGLA/IGLA_ASHA_Bound.v::champion_survives_pruning"

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------
log()  { echo "[eqy_check] $*"; }
warn() { echo "[eqy_check] WARNING: $*" >&2; }
fail() { echo "[eqy_check] ERROR: $*" >&2; exit 1; }

sha256_of() {
    if [[ -f "$1" ]]; then
        sha256sum "$1" | awk '{print $1}'
    else
        echo "MISSING"
    fi
}

timestamp_utc() {
    date -u +"%Y-%m-%dT%H:%M:%SZ"
}

get_git_sha() {
    git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo "unknown"
}

write_evidence_json() {
    local module="$1" src_sha="$2" t27c_sha="$3" eqy_ver="$4" yosys_ver="$5"
    local verdict="$6" ts="$7" evidence_path="$8"

    mkdir -p "${EVIDENCE_DIR}"
    python3 -c "
import json, sys
d = {
    'module':        '${module}',
    'src_sha':       '${src_sha}',
    't27c_sha':      '${t27c_sha}',
    'eqy_version':   '${eqy_ver}',
    'yosys_version': '${yosys_ver}',
    'verdict':       '${verdict}',
    'timestamp_utc': '${ts}',
    'evidence_path': '${evidence_path}',
    'anchor':        'phi^2 + phi^-2 = 3 · Wave-24 RVR-017 · DOI 10.5281/zenodo.19227877',
    't27c_commit':   '${T27C_COMMIT}',
    'coq_citation':  '${COQ_CITATIONS[${module}]:-UNKNOWN}',
    'r5_note':       'PENDING = t27c gen-verilog output not yet committed to build/t27c/'
}
print(json.dumps(d, indent=2))
" > "${evidence_path}"
}

# ---------------------------------------------------------------------------
# Toolchain version probing
# ---------------------------------------------------------------------------
probe_toolchain() {
    local yosys_ver eqy_ver
    yosys_ver="$(yosys --version 2>/dev/null | head -1 || echo "NOT_INSTALLED")"
    eqy_ver="$(eqy --version 2>/dev/null | head -1 || echo "NOT_INSTALLED")"
    echo "${yosys_ver}|${eqy_ver}"
}

# ---------------------------------------------------------------------------
# EQY config generator
# ---------------------------------------------------------------------------
write_eqy_config() {
    local module="$1" gold_v="$2" gate_v="$3" work_dir="$4"

    cat > "${work_dir}/${module}.eqy" <<EOF
[options]
depth 20

[gold]
read_verilog ${gold_v}
prep -top ${module}

[gate]
read_verilog ${gate_v}
prep -top ${module}

[script]
connect -set gclk \$gold.clk \$gate.clk
# Equivalence check on all outputs
EOF
}

# ---------------------------------------------------------------------------
# Run EQY for one module
# ---------------------------------------------------------------------------
run_eqy_module() {
    local module="$1"
    local src_file="${SRC_DIR}/${module}.v"
    local t27c_file="${BUILD_T27C_DIR}/${module}.v"
    local git_sha
    git_sha="$(get_git_sha)"
    local evidence_path="${EVIDENCE_DIR}/eqy_${git_sha}_${module}.json"
    local ts
    ts="$(timestamp_utc)"
    local toolchain_raw
    toolchain_raw="$(probe_toolchain)"
    local yosys_ver="${toolchain_raw%%|*}"
    local eqy_ver="${toolchain_raw##*|}"

    local src_sha
    src_sha="$(sha256_of "${src_file}")"
    local t27c_sha
    t27c_sha="$(sha256_of "${t27c_file}")"

    log "--------------------------------------------------------------"
    log "Module: ${module}"
    log "  src:   ${src_file}  (sha256: ${src_sha:0:16}...)"
    log "  t27c:  ${t27c_file} (sha256: ${t27c_sha:0:16}...)"
    log "  EQY:   ${eqy_ver}"
    log "  Yosys: ${yosys_ver}"

    # --- PENDING path: t27c file missing -----------------------------------
    if [[ "${t27c_sha}" == "MISSING" ]]; then
        warn "t27c-output-pending for ${module}: ${t27c_file} not found."
        warn "  Action: run 't27c gen-verilog' from gHashTag/t27 @ ${T27C_COMMIT}"
        warn "  and commit output to build/t27c/${module}.v"
        write_evidence_json "${module}" "${src_sha}" "MISSING" \
            "${eqy_ver}" "${yosys_ver}" "PENDING" "${ts}" "${evidence_path}"
        log "  Verdict: PENDING (t27c output not yet generated)"
        return 0
    fi

    # --- PENDING path: src file missing ------------------------------------
    if [[ "${src_sha}" == "MISSING" ]]; then
        warn "src file missing for ${module}: ${src_file}"
        write_evidence_json "${module}" "MISSING" "${t27c_sha}" \
            "${eqy_ver}" "${yosys_ver}" "PENDING" "${ts}" "${evidence_path}"
        log "  Verdict: PENDING (src file missing)"
        return 0
    fi

    # --- PENDING path: EQY not installed -----------------------------------
    if [[ "${eqy_ver}" == "NOT_INSTALLED" ]]; then
        warn "eqy binary not found. Install: pip install yosys-eqy"
        write_evidence_json "${module}" "${src_sha}" "${t27c_sha}" \
            "NOT_INSTALLED" "${yosys_ver}" "PENDING" "${ts}" "${evidence_path}"
        log "  Verdict: PENDING (eqy not installed in this environment)"
        return 0
    fi

    # --- Active EQY run ----------------------------------------------------
    local work_dir
    work_dir="$(mktemp -d /tmp/eqy_${module}_XXXXXX)"
    write_eqy_config "${module}" "${t27c_file}" "${src_file}" "${work_dir}"

    local verdict="FAIL"
    local eqy_exit=0
    eqy "${work_dir}/${module}.eqy" -d "${work_dir}/eqy_out" 2>&1 | \
        tee "${work_dir}/eqy_${module}.log" || eqy_exit=$?

    if [[ ${eqy_exit} -eq 0 ]]; then
        verdict="PASS"
        log "  Verdict: PASS (EQY exit 0)"
    else
        verdict="FAIL"
        warn "EQY reported non-equivalence for ${module} (exit ${eqy_exit})"
        log "  Verdict: FAIL"
    fi

    write_evidence_json "${module}" "${src_sha}" "${t27c_sha}" \
        "${eqy_ver}" "${yosys_ver}" "${verdict}" "${ts}" "${evidence_path}"

    rm -rf "${work_dir}"

    if [[ "${verdict}" == "FAIL" ]]; then
        return 1
    fi
    return 0
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    log "=============================================================="
    log "Yosys EQY t27c↔src equivalence check · Wave-24 RVR-017"
    log "Repo root: ${REPO_ROOT}"
    log "T27C_COMMIT: ${T27C_COMMIT}"
    log "=============================================================="

    mkdir -p "${EVIDENCE_DIR}"

    local any_fail=0
    local any_pending=0
    local results=()

    for module in "${MODULES[@]}"; do
        if run_eqy_module "${module}"; then
            # Check written evidence for PENDING
            local git_sha
            git_sha="$(get_git_sha)"
            local ev="${EVIDENCE_DIR}/eqy_${git_sha}_${module}.json"
            if [[ -f "${ev}" ]]; then
                local v
                v="$(python3 -c "import json; print(json.load(open('${ev}'))['verdict'])" 2>/dev/null || echo "UNKNOWN")"
                results+=("${module}:${v}")
                if [[ "${v}" == "PENDING" ]]; then
                    any_pending=1
                fi
            fi
        else
            results+=("${module}:FAIL")
            any_fail=1
        fi
    done

    log "=============================================================="
    log "SUMMARY"
    for r in "${results[@]}"; do
        log "  ${r%%:*}  →  ${r##*:}"
    done
    log "=============================================================="

    if [[ ${any_fail} -eq 1 ]]; then
        fail "One or more modules FAILED equivalence check. See evidence/ for details."
    fi

    if [[ ${any_pending} -eq 1 ]] && [[ "${EQY_STRICT}" == "1" ]]; then
        fail "One or more modules are PENDING and EQY_STRICT=1 is set."
    elif [[ ${any_pending} -eq 1 ]]; then
        warn "One or more modules are PENDING (t27c output not yet generated)."
        warn "This is expected pre-TTSKY26c. See docs/EQY_CHECK.md 'Current Status'."
        warn "Set EQY_STRICT=1 to treat PENDING as failure."
    fi

    log "All checks complete. Evidence written to ${EVIDENCE_DIR}/"
    exit 0
}

main "$@"
